### ISSUE TITLE
Scoring sequences

### ISSUE THREAD

**Issue by JesperGrud** [dev11ume/MinSeq-Find#1]
Hi,

Thank you for providing comprehensive code for your manuscript. I was trying to run it and got an error in the MinSeqScoring_1.m that wasn't obvious how to resolve. Specifically, I get this error: 

error: 'int_nu2x_c_arr' undefined near line 25, column 25
error: called from
    MinSeqScoring_1 at line 25 column 16

Can you provide some insight into where int_nu2x_c_arry should be derived from or how it should be declared?

Thanks

**Comment by JesperGrud** [comment]
Commenting out line 26 fixes the issue.

**Comment by JesperGrud** [comment]
Closed

**Comment by dev11ume** [comment]
Thank you for pointing out the error. I'll fix it.

Thanks,
Devesh
